# Generated by Django 3.2.5 on 2021-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='club_role',
            field=models.CharField(choices=[('APP', 'Applicant'), ('MEM', 'Member'), ('OFF', 'Officer'), ('OWN', 'Owner'), ('BAN', 'BannedMember')], default='APP', max_length=3),
        ),
    ]
