# Generated by Django 3.2.5 on 2021-12-06 18:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='organiser',
            field=models.ManyToManyField(related_name='organising_officers', to=settings.AUTH_USER_MODEL),
        ),
    ]
