# Generated by Django 3.2.5 on 2021-12-06 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_tournament_organiser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_participants',
            field=models.ManyToManyField(through='clubs.Player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TournamentRole',
        ),
    ]
