# Generated by Django 3.2.5 on 2021-11-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_user_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chess_experience_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Experienced'), (4, 'Expert'), (5, 'Professional')], default=1),
        ),
    ]
