# Generated by Django 3.2.5 on 2021-11-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_alter_user_chess_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_applicant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='chess_experience_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Experienced'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1),
        ),
    ]
