# Generated by Django 3.2.5 on 2021-11-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_auto_20211125_0152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRoles',
            new_name='Members',
        ),
    ]
