# Generated by Django 3.2.5 on 2021-11-25 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_rename_userroles_members'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Role',
        ),
        migrations.AlterField(
            model_name='club',
            name='club_name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Club name must consist of at least five alphanumericals', regex='^\\w{5,}$')]),
        ),
    ]
